const express=require('express'),multer=require('multer'),cors=require('cors'),morgan=require('morgan'),path=require('path'),fs=require('fs'),crypto=require('crypto'),Database=require('better-sqlite3'),helmet=require('helmet'),rateLimit=require('express-rate-limit');
const app=express(),PORT=process.env.PORT||3000;
const UPLOADS_DIR=path.join(__dirname,'public','uploads'),DB_DIR=path.join(__dirname,'database'),DB_PATH=path.join(DB_DIR,'fueltrack.db');
const ALLOWED_IMG_EXT=new Set(['.jpg','.jpeg','.png','.webp','.gif','.bmp']);
[UPLOADS_DIR,DB_DIR].forEach(d=>{if(!fs.existsSync(d))fs.mkdirSync(d,{recursive:true})});
let db;
function run(sql,p=[]){db.prepare(sql).run(...p)}
function all(sql,p=[]){return db.prepare(sql).all(...p)}
function get(sql,p=[]){return db.prepare(sql).get(...p)||null}
const uid=()=>crypto.randomUUID();
const hashPass=(pass,salt)=>{salt=salt||crypto.randomBytes(16).toString('hex');const h=crypto.pbkdf2Sync(pass,salt,100000,64,'sha512').toString('hex');return{salt,hash:h}};
const safeFn=fn=>{const base=path.basename(fn);if(!base||base.startsWith('.')||base!==fn)return null;return base;};
const safeInt=(v,def=50,max=500)=>{const n=parseInt(v);return isNaN(n)?def:Math.min(Math.max(n,1),max)};
const safeOffset=(v)=>{const n=parseInt(v);return isNaN(n)||n<0?0:n;};
const validatePassword=(p)=>{if(!p||p.length<8)return'Senha deve ter no mínimo 8 caracteres';return null;};
const safeFilePath=(filename)=>{const resolved=path.resolve(UPLOADS_DIR,filename);if(!resolved.startsWith(UPLOADS_DIR))return null;return resolved;};
const KM_SERVICE_TYPES=[{key:'oleo',label:'Oleo'},{key:'correia_dentada',label:'Correia Dentada'},{key:'pneus',label:'Pneus'},{key:'freios',label:'Freios'}];
const normalizeKmService=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'');
const validMonth=m=>/^\d{4}-\d{2}$/.test(m||'')?m:new Date().toISOString().slice(0,7);
const toNum=v=>{const n=parseFloat(v);return isNaN(n)?0:n;};
const normalizeDiscountType=t=>String(t||'').toLowerCase()==='percentual'?'percentual':'valor';
const normalizeNotaItems=items=>(Array.isArray(items)?items:[]).map(it=>({descricao:String(it?.descricao||'').trim().slice(0,300),quantidade:Math.max(toNum(it?.quantidade)||1,0),valor:Math.max(toNum(it?.valor),0)})).filter(it=>it.descricao&&it.quantidade>0);
const MATERIAL_STATUS=new Set(['orcamento','agendado','entregue','cancelado']);
const normalizeMaterialStatus=s=>MATERIAL_STATUS.has(String(s||''))?String(s):'orcamento';
function calcNotaTotals(subtotal,desconto,descontoTipo){
const tipo=normalizeDiscountType(descontoTipo),raw=Math.max(toNum(desconto),0),descontoAplicado=tipo==='percentual'?Math.min(subtotal*(raw/100),subtotal):Math.min(raw,subtotal),total=Math.max(subtotal-descontoAplicado,0);
return{desconto_tipo:tipo,desconto:raw,desconto_aplicado:descontoAplicado,total};
}
function enrichMaterialRow(row){
const quantidade=toNum(row.quantidade),custoUnit=toNum(row.valor_custo_unit),vendaUnit=toNum(row.valor_venda_unit),freteCusto=toNum(row.frete_custo),freteCobrado=toNum(row.frete_cobrado),taxas=toNum(row.taxas),subtotalCusto=quantidade*custoUnit,subtotalVenda=quantidade*vendaUnit,totalCusto=subtotalCusto+freteCusto+taxas,totalVenda=subtotalVenda+freteCobrado,lucro=totalVenda-totalCusto,margem=totalVenda>0?(lucro/totalVenda)*100:0;
return{...row,quantidade,valor_custo_unit:custoUnit,valor_venda_unit:vendaUnit,frete_custo:freteCusto,frete_cobrado:freteCobrado,taxas,subtotal_custo:subtotalCusto,subtotal_venda:subtotalVenda,total_custo:totalCusto,total_venda:totalVenda,lucro,margem_percentual:margem};
}
function collectVehicleKmPoints(vid){
const pts=[];
all("SELECT data AS d,hodometro AS km FROM abastecimentos WHERE veiculo_id=? AND hodometro>0",[vid]).forEach(r=>pts.push({data:r.d,km:+r.km||0}));
all("SELECT data AS d,km FROM checklists WHERE veiculo_id=? AND km>0",[vid]).forEach(r=>pts.push({data:r.d,km:+r.km||0}));
all("SELECT data_saida AS d,km_saida AS km FROM transferencias WHERE veiculo_id=? AND km_saida>0",[vid]).forEach(r=>pts.push({data:r.d,km:+r.km||0}));
all("SELECT data_retorno AS d,km_retorno AS km FROM transferencias WHERE veiculo_id=? AND data_retorno!='' AND km_retorno>0",[vid]).forEach(r=>pts.push({data:r.d,km:+r.km||0}));
all("SELECT data AS d,km_atual AS km FROM manutencoes WHERE veiculo_id=? AND km_atual>0",[vid]).forEach(r=>pts.push({data:r.d,km:+r.km||0}));
all("SELECT data AS d,km_horimetro AS km FROM notas_servico WHERE veiculo_id=? AND km_horimetro>0",[vid]).forEach(r=>pts.push({data:r.d,km:+r.km||0}));
return pts.filter(p=>p.data&&p.km>0).sort((a,b)=>String(a.data).localeCompare(String(b.data))||a.km-b.km);}
function buildKmPanelRow(v,mes,allControls){
const pts=collectVehicleKmPoints(v.id),monthPts=pts.filter(p=>String(p.data).slice(0,7)===mes),prevPts=pts.filter(p=>String(p.data).slice(0,7)<mes),currentKm=pts.length?pts[pts.length-1].km:(+v.km_ini||0),prevKm=prevPts.length?prevPts[prevPts.length-1].km:null,firstMonthKm=monthPts[0]?.km??null,lastMonthKm=monthPts[monthPts.length-1]?.km??null;
let monthStart=prevKm;
if(monthStart==null&&monthPts.length>1)monthStart=firstMonthKm;
if(monthStart==null&&(+(v.km_ini||0))>0)monthStart=+v.km_ini;
const monthEnd=lastMonthKm,monthTotal=monthEnd!=null?Math.max(monthEnd-(monthStart??0),0):0;
const controlMap=new Map((allControls||[]).filter(c=>c.veiculo_id===v.id).map(c=>[c.servico,c]));
const controles=KM_SERVICE_TYPES.map(t=>{const c=controlMap.get(t.key),previsao=+c?.previsao_km||0,restante=previsao?Math.round(previsao-currentKm):null,status=!previsao?'vazio':currentKm>=previsao?'vencido':restante<=1000?'atencao':'ok';return{servico:t.key,label:t.label,previsao_km:previsao||null,atual_km:currentKm||0,restante_km:restante,status,obs:c?.obs||''};});
return{id:v.id,placa:v.placa,nome:v.nome,marca:v.marca,modelo:v.modelo,tipo:v.tipo,km_atual:currentKm||0,km_inicial_mes:monthStart,km_final_mes:monthEnd,km_rodado_mes:monthTotal,leituras_mes:monthPts.length,controles};}

function initDb(){
db=new Database(DB_PATH);
db.pragma('journal_mode=WAL');
db.pragma('synchronous=NORMAL');
db.pragma('foreign_keys=ON');
db.exec(`CREATE TABLE IF NOT EXISTS usuarios(id TEXT PRIMARY KEY,nome TEXT NOT NULL,email TEXT DEFAULT '',login TEXT NOT NULL UNIQUE,senha_hash TEXT NOT NULL,senha_salt TEXT NOT NULL,perfil TEXT DEFAULT 'operador',ativo INTEGER DEFAULT 1,criado_em TEXT DEFAULT(datetime('now','localtime')),motorista_id TEXT DEFAULT '')`);
try{db.exec("ALTER TABLE usuarios ADD COLUMN motorista_id TEXT DEFAULT ''")}catch(e){}
db.exec(`CREATE TABLE IF NOT EXISTS sessoes(token TEXT PRIMARY KEY,usuario_id TEXT NOT NULL,criado_em TEXT DEFAULT(datetime('now','localtime')),expira_em TEXT NOT NULL)`);
db.exec(`CREATE TABLE IF NOT EXISTS maquinas(id TEXT PRIMARY KEY,nome TEXT NOT NULL,codigo TEXT NOT NULL UNIQUE,tipo TEXT DEFAULT '',descricao TEXT DEFAULT '',ano INTEGER,ativo INTEGER DEFAULT 1,criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS percursos(id TEXT PRIMARY KEY,maquina_id TEXT NOT NULL,maquina_nome TEXT DEFAULT '',maquina_codigo TEXT DEFAULT '',operador_id TEXT NOT NULL,operador_nome TEXT DEFAULT '',motorista_id TEXT DEFAULT '',motorista_nome TEXT DEFAULT '',inicio TEXT NOT NULL,fim TEXT DEFAULT '',lat_inicio REAL,lng_inicio REAL,endereco_inicio TEXT DEFAULT '',lat_fim REAL,lng_fim REAL,endereco_fim TEXT DEFAULT '',duracao_seg INTEGER DEFAULT 0,status TEXT DEFAULT 'em_andamento',criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE INDEX IF NOT EXISTS idx_percurso_status ON percursos(status)`);
db.exec(`CREATE INDEX IF NOT EXISTS idx_percurso_operador ON percursos(operador_id,status)`);
db.exec(`CREATE INDEX IF NOT EXISTS idx_percurso_maquina ON percursos(maquina_id,status)`);
db.exec(`CREATE TABLE IF NOT EXISTS auditoria(id TEXT PRIMARY KEY,usuario_id TEXT DEFAULT '',usuario_login TEXT DEFAULT '',acao TEXT NOT NULL,entidade TEXT DEFAULT '',entidade_id TEXT DEFAULT '',detalhes TEXT DEFAULT '',ip TEXT DEFAULT '',criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE INDEX IF NOT EXISTS idx_audit_data ON auditoria(criado_em)`);
db.exec(`CREATE TABLE IF NOT EXISTS alertas(id TEXT PRIMARY KEY,veiculo_id TEXT DEFAULT '',tipo TEXT NOT NULL DEFAULT 'manutencao',titulo TEXT NOT NULL,mensagem TEXT DEFAULT '',prioridade TEXT DEFAULT 'media',lido INTEGER DEFAULT 0,resolvido INTEGER DEFAULT 0,referencia_id TEXT DEFAULT '',criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS motoristas(id TEXT PRIMARY KEY,nome TEXT NOT NULL,cnh TEXT DEFAULT '',cnh_validade TEXT DEFAULT '',telefone TEXT DEFAULT '',email TEXT DEFAULT '',ativo INTEGER DEFAULT 1,criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS veiculos(id TEXT PRIMARY KEY,placa TEXT NOT NULL UNIQUE,nome TEXT DEFAULT '',marca TEXT DEFAULT '',modelo TEXT DEFAULT '',ano INTEGER,cor TEXT DEFAULT '',combustivel TEXT DEFAULT 'Gasolina',tanque REAL DEFAULT 0,km_ini REAL DEFAULT 0,criado_em TEXT DEFAULT(datetime('now','localtime')),ativo INTEGER DEFAULT 1,tipo TEXT DEFAULT 'carro')`);
try{db.exec("ALTER TABLE veiculos ADD COLUMN tipo TEXT DEFAULT 'carro'")}catch(e){}
db.exec(`CREATE TABLE IF NOT EXISTS abastecimentos(id TEXT PRIMARY KEY,veiculo_id TEXT NOT NULL,data TEXT NOT NULL,combustivel TEXT NOT NULL DEFAULT 'Gasolina',posto TEXT DEFAULT '',litros REAL NOT NULL,preco REAL NOT NULL,total REAL NOT NULL,hodometro REAL DEFAULT 0,km_rodados REAL DEFAULT 0,consumo REAL DEFAULT 0,cheio INTEGER DEFAULT 1,nota TEXT DEFAULT '',obs TEXT DEFAULT '',criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS fotos(id TEXT PRIMARY KEY,abastecimento_id TEXT NOT NULL,filename TEXT NOT NULL,criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS checklists(id TEXT PRIMARY KEY,veiculo_id TEXT NOT NULL,data TEXT NOT NULL,tipo TEXT DEFAULT 'saida',motorista TEXT DEFAULT '',km REAL DEFAULT 0,destino TEXT DEFAULT '',obs TEXT DEFAULT '',criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS checklist_itens(id TEXT PRIMARY KEY,checklist_id TEXT NOT NULL,item TEXT NOT NULL,ok INTEGER DEFAULT 0,obs TEXT DEFAULT '')`);
db.exec(`CREATE TABLE IF NOT EXISTS checklist_item_fotos(id TEXT PRIMARY KEY,checklist_item_id TEXT NOT NULL,filename TEXT NOT NULL,criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS transferencias(id TEXT PRIMARY KEY,veiculo_id TEXT NOT NULL,data_saida TEXT NOT NULL,data_retorno TEXT DEFAULT '',motorista_saida TEXT DEFAULT '',motorista_retorno TEXT DEFAULT '',km_saida REAL DEFAULT 0,km_retorno REAL DEFAULT 0,destino TEXT DEFAULT '',obs TEXT DEFAULT '',status TEXT DEFAULT 'aberto',criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS manutencoes(id TEXT PRIMARY KEY,veiculo_id TEXT NOT NULL,data TEXT NOT NULL,tipo TEXT DEFAULT 'preventiva',descricao TEXT DEFAULT '',oficina TEXT DEFAULT '',valor REAL DEFAULT 0,km_atual REAL DEFAULT 0,proxima_km REAL DEFAULT 0,proxima_data TEXT DEFAULT '',status TEXT DEFAULT 'concluido',obs TEXT DEFAULT '',criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS manutencao_fotos(id TEXT PRIMARY KEY,manutencao_id TEXT NOT NULL,filename TEXT NOT NULL,criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS km_controles(id TEXT PRIMARY KEY,veiculo_id TEXT NOT NULL,servico TEXT NOT NULL,previsao_km REAL DEFAULT 0,obs TEXT DEFAULT '',atualizado_em TEXT DEFAULT(datetime('now','localtime')),UNIQUE(veiculo_id,servico))`);
db.exec(`CREATE TABLE IF NOT EXISTS notas_servico(id TEXT PRIMARY KEY,veiculo_id TEXT NOT NULL,data TEXT NOT NULL,km_horimetro REAL DEFAULT 0,oficina TEXT DEFAULT '',numero TEXT DEFAULT '',desconto REAL DEFAULT 0,desconto_tipo TEXT DEFAULT 'valor',total REAL DEFAULT 0,obs TEXT DEFAULT '',criado_em TEXT DEFAULT(datetime('now','localtime')))`);try{db.exec("ALTER TABLE notas_servico ADD COLUMN desconto_tipo TEXT DEFAULT 'valor'")}catch(e){}
db.exec(`CREATE TABLE IF NOT EXISTS nota_servico_itens(id TEXT PRIMARY KEY,nota_id TEXT NOT NULL,descricao TEXT NOT NULL,quantidade REAL DEFAULT 1,valor REAL DEFAULT 0,criado_em TEXT DEFAULT(datetime('now','localtime')))`);
db.exec(`CREATE TABLE IF NOT EXISTS entregas_materiais(id TEXT PRIMARY KEY,data_pedido TEXT NOT NULL,data_entrega TEXT DEFAULT '',cliente TEXT NOT NULL,telefone TEXT DEFAULT '',material TEXT NOT NULL,fornecedor TEXT DEFAULT '',veiculo_id TEXT DEFAULT '',motorista TEXT DEFAULT '',quantidade REAL DEFAULT 0,unidade TEXT DEFAULT 'Carrada',valor_custo_unit REAL DEFAULT 0,valor_venda_unit REAL DEFAULT 0,frete_custo REAL DEFAULT 0,frete_cobrado REAL DEFAULT 0,taxas REAL DEFAULT 0,status TEXT DEFAULT 'orcamento',endereco TEXT DEFAULT '',cidade TEXT DEFAULT '',obs TEXT DEFAULT '',criado_em TEXT DEFAULT(datetime('now','localtime')))`);try{db.exec("ALTER TABLE entregas_materiais ADD COLUMN taxas REAL DEFAULT 0")}catch(e){}
db.exec(`CREATE TABLE IF NOT EXISTS config(chave TEXT PRIMARY KEY,valor TEXT)`);
const cfgDefaults={'empresa':'iLnet','responsavel':'','alerta_dias_antecedencia':'15','alerta_km_antecedencia':'1000','alerta_km_antecedencia_moto':'500','smtp_host':'','smtp_port':'587','smtp_user':'','smtp_pass':'','alerta_email':''};
Object.entries(cfgDefaults).forEach(([k,v])=>run(`INSERT OR IGNORE INTO config VALUES(?,?)`,[ k,v]));
const ae=get("SELECT id FROM usuarios WHERE perfil='admin' LIMIT 1");
if(!ae){const tmpPass=crypto.randomBytes(6).toString('hex');const{salt,hash}=hashPass(tmpPass);run("INSERT INTO usuarios(id,nome,email,login,senha_hash,senha_salt,perfil)VALUES(?,?,?,?,?,?,?)",[uid(),'Administrador','admin@ilnet.com','admin',hash,salt,'admin']);console.log('  Usuário admin criado');console.log('  Senha temporária: '+tmpPass);console.log('  [AVISO] TROQUE A SENHA NO PRIMEIRO LOGIN!')}
console.log('  Banco (better-sqlite3 + WAL):',DB_PATH)}

app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));
app.use(cors({origin:(_,cb)=>cb(null,true),credentials:true}));
app.use(morgan(process.env.NODE_ENV==='production'?'combined':'dev'));
app.use(express.json({limit:'1mb'}));
app.use('/uploads',(_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Content-Security-Policy',"default-src 'none'; img-src 'self'");next()},express.static(path.join(__dirname,'public','uploads')));
app.use(express.static(path.join(__dirname,'public')));

function authMiddleware(req,res,next){const token=req.headers['authorization']?.replace('Bearer ','');if(!token)return res.status(401).json({error:'Token obrigatório'});const s=get("SELECT s.*,u.nome,u.login,u.perfil,u.email,u.id AS uid,u.motorista_id FROM sessoes s JOIN usuarios u ON u.id=s.usuario_id WHERE s.token=? AND u.ativo=1",[token]);if(!s)return res.status(401).json({error:'Sessão inválida'});if(new Date(s.expira_em)<new Date()){run("DELETE FROM sessoes WHERE token=?",[token]);return res.status(401).json({error:'Expirada'})}req.user=s;run("UPDATE sessoes SET expira_em=? WHERE token=?",[new Date(Date.now()+8*3600000).toISOString(),token]);next()}
function adminOnly(req,res,next){if(req.user.perfil!=='admin')return res.status(403).json({error:'Admin only'});next()}
function audit(req,acao,entidade,entidade_id,detalhes){try{run("INSERT INTO auditoria(id,usuario_id,usuario_login,acao,entidade,entidade_id,detalhes,ip)VALUES(?,?,?,?,?,?,?,?)",[uid(),req.user?.uid||'',req.user?.login||'',acao,entidade||'',entidade_id||'',JSON.stringify(detalhes||{}).slice(0,2000),(req.ip||'').slice(0,60)])}catch(e){}}
function buildUserPayload(u){const motorista=u.motorista_id?get("SELECT id,nome,cnh,telefone FROM motoristas WHERE id=?",[u.motorista_id]):null;return{id:u.id||u.uid,nome:u.nome,login:u.login,perfil:u.perfil,email:u.email,motorista_id:u.motorista_id||'',motorista}}

// AUTH — rate limiting (5 tentativas por 2 min por IP, bloqueio exponencial)
const loginAttempts=new Map();
function checkRateLimit(ip){const now=Date.now();const entry=loginAttempts.get(ip)||{count:0,resetAt:now+120000,lockUntil:0};if(now<entry.lockUntil)return false;if(now>entry.resetAt){entry.count=0;entry.resetAt=now+120000;entry.lockUntil=0;}entry.count++;loginAttempts.set(ip,entry);if(entry.count>5){entry.lockUntil=now+Math.min(entry.count*60000,600000);return false;}return true;}
setInterval(()=>{const now=Date.now();for(const[k,v]of loginAttempts)if(now>v.resetAt&&now>v.lockUntil)loginAttempts.delete(k);},120000);
// Limpeza de sessões expiradas a cada hora
setInterval(()=>{try{run("DELETE FROM sessoes WHERE expira_em < datetime('now','localtime')");}catch(e){}},3600000);

app.post('/api/auth/login',(req,res)=>{if(!checkRateLimit(req.ip))return res.status(429).json({error:'Muitas tentativas. Aguarde alguns minutos.'});const{login,senha}=req.body;if(!login||!senha)return res.status(400).json({error:'Login e senha obrigatórios'});const u=get("SELECT * FROM usuarios WHERE login=? AND ativo=1",[login]);if(!u)return res.status(401).json({error:'Usuário ou senha inválidos'});const{hash}=hashPass(senha,u.senha_salt);if(hash!==u.senha_hash)return res.status(401).json({error:'Usuário ou senha inválidos'});run("DELETE FROM sessoes WHERE usuario_id=? AND expira_em<datetime('now','localtime')",[u.id]);const token=crypto.randomBytes(32).toString('hex');run("INSERT INTO sessoes(token,usuario_id,expira_em)VALUES(?,?,?)",[token,u.id,new Date(Date.now()+8*3600000).toISOString()]);try{run("INSERT INTO auditoria(id,usuario_id,usuario_login,acao,entidade,ip)VALUES(?,?,?,?,?,?)",[uid(),u.id,u.login,'login','sessao',(req.ip||'').slice(0,60)])}catch(e){}res.json({token,user:buildUserPayload(u)})});
app.post('/api/auth/logout',(req,res)=>{const t=req.headers['authorization']?.replace('Bearer ','');if(t)run("DELETE FROM sessoes WHERE token=?",[t]);res.json({ok:true})});
app.get('/api/auth/me',authMiddleware,(req,res)=>res.json(buildUserPayload(req.user)));
app.put('/api/auth/senha',authMiddleware,(req,res)=>{const{senha_atual,nova_senha}=req.body;if(!senha_atual||!nova_senha)return res.status(400).json({error:'Campos obrigatórios'});const pwErr=validatePassword(nova_senha);if(pwErr)return res.status(400).json({error:pwErr});const u=get("SELECT * FROM usuarios WHERE id=?",[req.user.uid]);const{hash:ch}=hashPass(senha_atual,u.senha_salt);if(ch!==u.senha_hash)return res.status(401).json({error:'Senha atual incorreta'});const{salt,hash}=hashPass(nova_senha);run("UPDATE usuarios SET senha_hash=?,senha_salt=? WHERE id=?",[hash,salt,req.user.uid]);res.json({ok:true})});

// USERS
const PERFIS=new Set(['admin','operador','operador_maquina']);
const normalizePerfil=p=>PERFIS.has(p)?p:'operador';
app.get('/api/usuarios',authMiddleware,adminOnly,(_,res)=>res.json(all("SELECT u.id,u.nome,u.email,u.login,u.perfil,u.ativo,u.criado_em,u.motorista_id,m.nome AS motorista_nome FROM usuarios u LEFT JOIN motoristas m ON m.id=u.motorista_id ORDER BY u.nome")));
app.post('/api/usuarios',authMiddleware,adminOnly,(req,res)=>{const{nome,email,login,senha,perfil,motorista_id}=req.body;if(!nome||!login||!senha)return res.status(400).json({error:'Nome,login,senha'});const pwErr=validatePassword(senha);if(pwErr)return res.status(400).json({error:pwErr});const np=normalizePerfil(perfil);if(np==='operador_maquina'&&!motorista_id)return res.status(400).json({error:'Operador de Máquina precisa estar vinculado a um motorista'});if(motorista_id&&!get("SELECT id FROM motoristas WHERE id=? AND ativo=1",[motorista_id]))return res.status(400).json({error:'Motorista inválido'});const{salt,hash}=hashPass(senha);const id=uid();try{run("INSERT INTO usuarios(id,nome,email,login,senha_hash,senha_salt,perfil,motorista_id)VALUES(?,?,?,?,?,?,?,?)",[id,nome,email||'',login,hash,salt,np,motorista_id||'']);audit(req,'criar','usuario',id,{login,perfil:np,motorista_id:motorista_id||''});res.json(get("SELECT u.id,u.nome,u.email,u.login,u.perfil,u.ativo,u.criado_em,u.motorista_id,m.nome AS motorista_nome FROM usuarios u LEFT JOIN motoristas m ON m.id=u.motorista_id WHERE u.id=?",[id]))}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'Login já existe':'Erro ao criar usuário'})}});
app.put('/api/usuarios/:id',authMiddleware,adminOnly,(req,res)=>{const{nome,email,perfil,ativo,senha,motorista_id}=req.body;const np=normalizePerfil(perfil);const mid=motorista_id===undefined?get("SELECT motorista_id FROM usuarios WHERE id=?",[req.params.id])?.motorista_id||'':(motorista_id||'');if(np==='operador_maquina'&&!mid)return res.status(400).json({error:'Operador de Máquina precisa estar vinculado a um motorista'});if(mid&&!get("SELECT id FROM motoristas WHERE id=? AND ativo=1",[mid]))return res.status(400).json({error:'Motorista inválido'});run("UPDATE usuarios SET nome=?,email=?,perfil=?,ativo=?,motorista_id=? WHERE id=?",[nome||'',email||'',np,ativo!==undefined?ativo:1,mid,req.params.id]);if(senha){const pwErr=validatePassword(senha);if(pwErr)return res.status(400).json({error:pwErr});const{salt,hash}=hashPass(senha);run("UPDATE usuarios SET senha_hash=?,senha_salt=? WHERE id=?",[hash,salt,req.params.id])}audit(req,'editar','usuario',req.params.id,{perfil:np,motorista_id:mid,senha_alterada:!!senha});res.json(get("SELECT u.id,u.nome,u.email,u.login,u.perfil,u.ativo,u.criado_em,u.motorista_id,m.nome AS motorista_nome FROM usuarios u LEFT JOIN motoristas m ON m.id=u.motorista_id WHERE u.id=?",[req.params.id]))});
app.delete('/api/usuarios/:id',authMiddleware,adminOnly,(req,res)=>{if(req.params.id===req.user.uid)return res.status(400).json({error:'Não pode excluir a si mesmo'});const u=get("SELECT perfil,nome,login FROM usuarios WHERE id=?",[req.params.id]);if(!u)return res.status(404).json({error:'Usuário não encontrado'});if(u.perfil==='admin'){const outros=get("SELECT COUNT(*)AS n FROM usuarios WHERE perfil='admin' AND ativo=1 AND id!=?",[req.params.id])?.n||0;if(outros===0)return res.status(400).json({error:'Não pode excluir o único admin do sistema'})}run("DELETE FROM sessoes WHERE usuario_id=?",[req.params.id]);run("DELETE FROM usuarios WHERE id=?",[req.params.id]);audit(req,'excluir','usuario',req.params.id,{login:u.login,nome:u.nome});res.json({ok:true})});

// MOTORISTAS
app.get('/api/motoristas',authMiddleware,(_,res)=>res.json(all("SELECT * FROM motoristas WHERE ativo=1 ORDER BY nome")));
app.post('/api/motoristas',authMiddleware,(req,res)=>{const{nome,cnh,cnh_validade,telefone,email}=req.body;if(!nome)return res.status(400).json({error:'Nome'});const id=uid();run("INSERT INTO motoristas(id,nome,cnh,cnh_validade,telefone,email)VALUES(?,?,?,?,?,?)",[id,nome,cnh||'',cnh_validade||'',telefone||'',email||'']);res.json(get("SELECT * FROM motoristas WHERE id=?",[id]))});
app.put('/api/motoristas/:id',authMiddleware,(req,res)=>{const{nome,cnh,cnh_validade,telefone,email}=req.body;run("UPDATE motoristas SET nome=?,cnh=?,cnh_validade=?,telefone=?,email=? WHERE id=?",[nome||'',cnh||'',cnh_validade||'',telefone||'',email||'',req.params.id]);res.json(get("SELECT * FROM motoristas WHERE id=?",[req.params.id]))});
app.delete('/api/motoristas/:id',authMiddleware,(req,res)=>{run("UPDATE motoristas SET ativo=0 WHERE id=?",[req.params.id]);res.json({ok:true})});

// ALERTAS
app.get('/api/alertas',authMiddleware,(req,res)=>{const{lido}=req.query;const limit=safeInt(req.query.limit,50,200);let sql="SELECT a.*,v.placa,v.nome AS v_nome FROM alertas a LEFT JOIN veiculos v ON v.id=a.veiculo_id WHERE 1=1";const p=[];if(lido!==undefined){sql+=' AND a.lido=?';p.push(+lido)}sql+=' ORDER BY a.criado_em DESC LIMIT ?';p.push(limit);res.json(all(sql,p))});
app.get('/api/alertas/count',authMiddleware,(_,res)=>res.json({count:get("SELECT COUNT(*)AS n FROM alertas WHERE lido=0 AND resolvido=0")?.n||0}));
app.put('/api/alertas/:id/lido',authMiddleware,(req,res)=>{run("UPDATE alertas SET lido=1 WHERE id=?",[req.params.id]);res.json({ok:true})});
app.put('/api/alertas/ler-todos',authMiddleware,(_,res)=>{run("UPDATE alertas SET lido=1 WHERE lido=0");res.json({ok:true})});
app.put('/api/alertas/:id/resolver',authMiddleware,(req,res)=>{run("UPDATE alertas SET resolvido=1,lido=1 WHERE id=?",[req.params.id]);res.json({ok:true})});
app.delete('/api/alertas/:id',authMiddleware,(req,res)=>{run("DELETE FROM alertas WHERE id=?",[req.params.id]);res.json({ok:true})});

app.post('/api/alertas/verificar',authMiddleware,(req,res)=>{
const cfgDias=+(get("SELECT valor FROM config WHERE chave='alerta_dias_antecedencia'")?.valor||15);
const cfgKmCarro=+(get("SELECT valor FROM config WHERE chave='alerta_km_antecedencia'")?.valor||1000);
const cfgKmMoto=+(get("SELECT valor FROM config WHERE chave='alerta_km_antecedencia_moto'")?.valor||500);
const ms=all("SELECT m.*,v.placa,v.nome AS v_nome,v.tipo AS v_tipo FROM manutencoes m JOIN veiculos v ON v.id=m.veiculo_id WHERE v.ativo=1 AND(m.proxima_data!='' OR m.proxima_km>0)");
let created=0;const hoje=new Date();
ms.forEach(m=>{
const cfgKm=m.v_tipo==='moto'?cfgKmMoto:cfgKmCarro;
if(m.proxima_data){const diff=Math.ceil((new Date(m.proxima_data)-hoje)/864e5);if(diff<=cfgDias&&!get("SELECT id FROM alertas WHERE referencia_id=? AND tipo='manutencao_data' AND resolvido=0",[m.id])){const pri=diff<=0?'critica':diff<=5?'alta':'media';run("INSERT INTO alertas(id,veiculo_id,tipo,titulo,mensagem,prioridade,referencia_id)VALUES(?,?,?,?,?,?,?)",[uid(),m.veiculo_id,'manutencao_data',diff<=0?`[!] VENCIDA — ${m.placa}`:`Manutenção em ${diff}d — ${m.placa}`,`${m.descricao||m.tipo} em ${m.proxima_data}`,pri,m.id]);created++}}
if(m.proxima_km>0){const ka=get("SELECT MAX(hodometro)AS km FROM abastecimentos WHERE veiculo_id=? AND hodometro>0",[m.veiculo_id])?.km||m.km_atual||0;const rest=m.proxima_km-ka;if(rest<=cfgKm&&rest>-99999&&!get("SELECT id FROM alertas WHERE referencia_id=? AND tipo='manutencao_km' AND resolvido=0",[m.id])){const pri=rest<=0?'critica':rest<=300?'alta':'media';run("INSERT INTO alertas(id,veiculo_id,tipo,titulo,mensagem,prioridade,referencia_id)VALUES(?,?,?,?,?,?,?)",[uid(),m.veiculo_id,'manutencao_km',rest<=0?`[!] KM VENCIDO — ${m.placa}`:`${Math.round(rest)}km — ${m.placa}`,`${m.descricao||m.tipo} em ${m.proxima_km}km. Atual:${Math.round(ka)}km`,pri,m.id]);created++}}});
all("SELECT * FROM motoristas WHERE ativo=1 AND cnh_validade!=''").forEach(mot=>{const diff=Math.ceil((new Date(mot.cnh_validade)-hoje)/864e5);if(diff<=30&&!get("SELECT id FROM alertas WHERE referencia_id=? AND tipo='cnh' AND resolvido=0",[mot.id])){run("INSERT INTO alertas(id,veiculo_id,tipo,titulo,mensagem,prioridade,referencia_id)VALUES(?,?,?,?,?,?,?)",[uid(),'','cnh',diff<=0?`[!] CNH VENCIDA — ${mot.nome}`:`CNH ${diff}d — ${mot.nome}`,`Validade: ${mot.cnh_validade}`,diff<=0?'critica':diff<=7?'alta':'media',mot.id]);created++}});
res.json({created,message:`${created} alertas gerados`})});

app.post('/api/alertas/enviar-email',authMiddleware,adminOnly,async(req,res)=>{
const sh=get("SELECT valor FROM config WHERE chave='smtp_host'")?.valor,sp=get("SELECT valor FROM config WHERE chave='smtp_port'")?.valor||'587',su=get("SELECT valor FROM config WHERE chave='smtp_user'")?.valor,spw=get("SELECT valor FROM config WHERE chave='smtp_pass'")?.valor,ae=get("SELECT valor FROM config WHERE chave='alerta_email'")?.valor;
if(!sh||!su||!ae)return res.status(400).json({error:'Configure SMTP nas Configurações'});
try{const nm=require('nodemailer');const t=nm.createTransport({host:sh,port:+sp,secure:+sp===465,auth:{user:su,pass:spw}});const als=all("SELECT a.*,v.placa FROM alertas a LEFT JOIN veiculos v ON v.id=a.veiculo_id WHERE a.lido=0 AND a.resolvido=0");if(!als.length)return res.json({sent:false,message:'Nenhum pendente'});const emp=get("SELECT valor FROM config WHERE chave='empresa'")?.valor||'iLnet';let html=`<h2>Alertas — ${emp}</h2><table border=1 cellpadding=8 style="border-collapse:collapse;font-family:sans-serif"><tr style="background:#0a1e30;color:#fff"><th>Prioridade</th><th>Veículo</th><th>Alerta</th></tr>`;als.forEach(a=>{const c=a.prioridade==='critica'?'#e05252':a.prioridade==='alta'?'#f5923a':'#f5c842';html+=`<tr><td style="color:${c};font-weight:bold">${a.prioridade.toUpperCase()}</td><td>${a.placa||'—'}</td><td>${a.titulo}<br><small>${a.mensagem}</small></td></tr>`});html+='</table>';await t.sendMail({from:`"${emp}" <${su}>`,to:ae,subject:`[${emp}] ${als.length} alerta(s)`,html});res.json({sent:true,count:als.length})}catch(e){res.status(e.code==='MODULE_NOT_FOUND'?400:500).json({error:e.code==='MODULE_NOT_FOUND'?'npm install nodemailer':e.message})}});

const mkUpload=()=>multer({storage:multer.diskStorage({destination:(_,__,cb)=>cb(null,UPLOADS_DIR),filename:(_,f,cb)=>{const ext=(path.extname(f.originalname).toLowerCase()||'.jpg');if(!ALLOWED_IMG_EXT.has(ext))return cb(new Error('Extensão não permitida'));cb(null,Date.now()+'-'+crypto.randomBytes(8).toString('hex')+ext)}}),limits:{fileSize:10*1024*1024},fileFilter:(_,f,cb)=>{if(!f.mimetype.startsWith('image/'))return cb(new Error('Apenas imagens'));const ext=path.extname(f.originalname).toLowerCase();if(!ALLOWED_IMG_EXT.has(ext))return cb(new Error('Extensão não permitida: '+ext));cb(null,true)}});
const upload=mkUpload();

// VEÍCULOS
app.get('/api/veiculos',authMiddleware,(_,res)=>res.json(all("SELECT v.*,COUNT(a.id)AS total_abast,COALESCE(SUM(a.total),0)AS total_gasto,COALESCE(SUM(a.litros),0)AS total_litros,MAX(a.hodometro)AS hodometro_atual FROM veiculos v LEFT JOIN abastecimentos a ON a.veiculo_id=v.id WHERE v.ativo=1 GROUP BY v.id ORDER BY v.placa")));
app.post('/api/veiculos',authMiddleware,(req,res)=>{const{placa,nome,marca,modelo,ano,cor,combustivel,tanque,km_ini,tipo}=req.body;if(!placa)return res.status(400).json({error:'Placa'});const id=uid();try{run("INSERT INTO veiculos(id,placa,nome,marca,modelo,ano,cor,combustivel,tanque,km_ini,tipo)VALUES(?,?,?,?,?,?,?,?,?,?,?)",[id,placa.toUpperCase(),nome||'',marca||'',modelo||'',ano||null,cor||'',combustivel||'Gasolina',tanque||0,km_ini||0,tipo||'carro']);res.json(get('SELECT*FROM veiculos WHERE id=?',[id]))}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'Placa já existe':'Erro ao criar veículo'})}});
app.put('/api/veiculos/:id',authMiddleware,(req,res)=>{const{placa,nome,marca,modelo,ano,cor,combustivel,tanque,km_ini,tipo}=req.body;run("UPDATE veiculos SET placa=?,nome=?,marca=?,modelo=?,ano=?,cor=?,combustivel=?,tanque=?,km_ini=?,tipo=? WHERE id=?",[placa?.toUpperCase()||'',nome||'',marca||'',modelo||'',ano||null,cor||'',combustivel||'',tanque||0,km_ini||0,tipo||'carro',req.params.id]);res.json(get('SELECT*FROM veiculos WHERE id=?',[req.params.id]))});
app.delete('/api/veiculos/:id',authMiddleware,(req,res)=>{run('UPDATE veiculos SET ativo=0 WHERE id=?',[req.params.id]);res.json({ok:true})});

// ABASTECIMENTOS
app.get('/api/abastecimentos',authMiddleware,(req,res)=>{const{veiculo_id,combustivel,mes,busca}=req.query;const limit=safeInt(req.query.limit,200,500);const offset=safeOffset(req.query.offset);let sql="SELECT a.*,v.placa,v.nome AS v_nome,v.marca,v.modelo FROM abastecimentos a JOIN veiculos v ON v.id=a.veiculo_id WHERE v.ativo=1";const p=[];if(veiculo_id){sql+=' AND a.veiculo_id=?';p.push(veiculo_id)}if(combustivel){sql+=' AND a.combustivel=?';p.push(combustivel)}if(mes){sql+=" AND substr(a.data,1,7)=?";p.push(mes)}if(busca){sql+=' AND(v.placa LIKE? OR a.posto LIKE? OR a.combustivel LIKE?)';const b='%'+busca+'%';p.push(b,b,b)}sql+=' ORDER BY a.data DESC LIMIT ? OFFSET ?';p.push(limit,offset);const rows=all(sql,p);rows.forEach(r=>{const f=all('SELECT filename FROM fotos WHERE abastecimento_id=?',[r.id]);r.fotos=f.map(x=>'/uploads/'+x.filename);r.fotos_count=f.length});res.json(rows)});
app.get('/api/abastecimentos/:id',authMiddleware,(req,res)=>{const a=get('SELECT*FROM abastecimentos WHERE id=?',[req.params.id]);if(!a)return res.status(404).json({error:'404'});a.fotos=all('SELECT filename FROM fotos WHERE abastecimento_id=?',[req.params.id]).map(f=>'/uploads/'+f.filename);res.json(a)});
app.post('/api/abastecimentos',authMiddleware,(req,res)=>{const{veiculo_id,data,combustivel,posto,litros,preco,total,hodometro,km_rodados,consumo,cheio,nota,obs}=req.body;if(!veiculo_id||!data||!litros||!preco)return res.status(400).json({error:'Campos obrigatórios'});const id=uid();run("INSERT INTO abastecimentos(id,veiculo_id,data,combustivel,posto,litros,preco,total,hodometro,km_rodados,consumo,cheio,nota,obs)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[id,veiculo_id,data,combustivel||'Gasolina',posto||'',+litros,+preco,+(total||litros*preco),+hodometro||0,+km_rodados||0,+consumo||0,cheio?1:0,nota||'',obs||'']);res.json(get('SELECT*FROM abastecimentos WHERE id=?',[id]))});
app.put('/api/abastecimentos/:id',authMiddleware,(req,res)=>{const{veiculo_id,data,combustivel,posto,litros,preco,total,hodometro,km_rodados,consumo,cheio,nota,obs}=req.body;run("UPDATE abastecimentos SET veiculo_id=?,data=?,combustivel=?,posto=?,litros=?,preco=?,total=?,hodometro=?,km_rodados=?,consumo=?,cheio=?,nota=?,obs=? WHERE id=?",[veiculo_id,data,combustivel,posto||'',+litros,+preco,+total,+hodometro||0,+km_rodados||0,+consumo||0,cheio?1:0,nota||'',obs||'',req.params.id]);res.json(get('SELECT*FROM abastecimentos WHERE id=?',[req.params.id]))});
app.delete('/api/abastecimentos/:id',authMiddleware,(req,res)=>{all('SELECT filename FROM fotos WHERE abastecimento_id=?',[req.params.id]).forEach(f=>{const fn=safeFn(f.filename);if(!fn)return;const p=safeFilePath(fn);if(p&&fs.existsSync(p))fs.unlinkSync(p)});run('DELETE FROM fotos WHERE abastecimento_id=?',[req.params.id]);run('DELETE FROM abastecimentos WHERE id=?',[req.params.id]);res.json({ok:true})});
app.post('/api/fotos/:aid',authMiddleware,upload.array('fotos',20),(req,res)=>{const saved=(req.files||[]).map(f=>{const id=uid();run('INSERT INTO fotos(id,abastecimento_id,filename)VALUES(?,?,?)',[id,req.params.aid,f.filename]);return{id,url:'/uploads/'+f.filename}});res.json(saved)});
app.delete('/api/fotos/:fn',authMiddleware,(req,res)=>{const fn=safeFn(req.params.fn);if(!fn)return res.status(400).json({error:'Nome de arquivo inválido'});const p=path.join(UPLOADS_DIR,fn);if(fs.existsSync(p))fs.unlinkSync(p);run('DELETE FROM fotos WHERE filename=?',[fn]);res.json({ok:true})});

// CHECKLIST
app.get('/api/checklists',authMiddleware,(req,res)=>{const{veiculo_id,tipo}=req.query;const limit=safeInt(req.query.limit,50,200);let sql="SELECT c.*,v.placa,v.nome AS v_nome FROM checklists c JOIN veiculos v ON v.id=c.veiculo_id WHERE v.ativo=1";const p=[];if(veiculo_id){sql+=' AND c.veiculo_id=?';p.push(veiculo_id)}if(tipo){sql+=' AND c.tipo=?';p.push(tipo)}sql+=' ORDER BY c.data DESC LIMIT ?';p.push(limit);const rows=all(sql,p);rows.forEach(r=>{r.itens=all('SELECT*FROM checklist_itens WHERE checklist_id=?',[r.id]);r.itens.forEach(it=>{it.fotos=all('SELECT filename FROM checklist_item_fotos WHERE checklist_item_id=?',[it.id]).map(f=>'/uploads/'+f.filename)})});res.json(rows)});
app.post('/api/checklists',authMiddleware,(req,res)=>{const{veiculo_id,data,tipo,motorista,km,destino,obs,itens}=req.body;if(!veiculo_id||!data)return res.status(400).json({error:'Obrigatórios'});const id=uid();run("INSERT INTO checklists(id,veiculo_id,data,tipo,motorista,km,destino,obs)VALUES(?,?,?,?,?,?,?,?)",[id,veiculo_id,data,tipo||'saida',motorista||'',+km||0,destino||'',obs||'']);const savedItens=[];(itens||[]).forEach(it=>{const iid=uid();run('INSERT INTO checklist_itens(id,checklist_id,item,ok,obs)VALUES(?,?,?,?,?)',[iid,id,it.item,it.ok?1:0,it.obs||'']);savedItens.push({id:iid,item:it.item,ok:it.ok?1:0,obs:it.obs||''})});const row=get('SELECT*FROM checklists WHERE id=?',[id]);row.itens=savedItens;res.json(row)});
app.post('/api/checklist-itens/:item_id/fotos',authMiddleware,upload.array('fotos',20),(req,res)=>{const saved=(req.files||[]).map(f=>{const id=uid();run('INSERT INTO checklist_item_fotos(id,checklist_item_id,filename)VALUES(?,?,?)',[id,req.params.item_id,f.filename]);return{id,url:'/uploads/'+f.filename}});res.json(saved)});
app.delete('/api/checklist-item-fotos/:fn',authMiddleware,(req,res)=>{const fn=safeFn(req.params.fn);if(!fn)return res.status(400).json({error:'Nome de arquivo inválido'});const p=path.join(UPLOADS_DIR,fn);if(fs.existsSync(p))fs.unlinkSync(p);run('DELETE FROM checklist_item_fotos WHERE filename=?',[fn]);res.json({ok:true})});
app.delete('/api/checklists/:id',authMiddleware,(req,res)=>{const itens=all('SELECT id FROM checklist_itens WHERE checklist_id=?',[req.params.id]);itens.forEach(it=>{all('SELECT filename FROM checklist_item_fotos WHERE checklist_item_id=?',[it.id]).forEach(f=>{const fn=safeFn(f.filename);if(!fn)return;const p=safeFilePath(fn);if(p&&fs.existsSync(p))fs.unlinkSync(p)});run('DELETE FROM checklist_item_fotos WHERE checklist_item_id=?',[it.id])});run('DELETE FROM checklist_itens WHERE checklist_id=?',[req.params.id]);run('DELETE FROM checklists WHERE id=?',[req.params.id]);res.json({ok:true})});

// TRANSFERÊNCIAS
app.get('/api/transferencias',authMiddleware,(req,res)=>{const{veiculo_id,status}=req.query;const limit=safeInt(req.query.limit,100,500);let sql="SELECT t.*,v.placa,v.nome AS v_nome,v.marca,v.modelo FROM transferencias t JOIN veiculos v ON v.id=t.veiculo_id WHERE v.ativo=1";const p=[];if(veiculo_id){sql+=' AND t.veiculo_id=?';p.push(veiculo_id)}if(status){sql+=' AND t.status=?';p.push(status)}sql+=' ORDER BY t.data_saida DESC LIMIT ?';p.push(limit);res.json(all(sql,p))});
app.post('/api/transferencias',authMiddleware,(req,res)=>{const{veiculo_id,data_saida,motorista_saida,km_saida,destino,obs}=req.body;if(!veiculo_id||!data_saida)return res.status(400).json({error:'Obrigatórios'});const id=uid();run("INSERT INTO transferencias(id,veiculo_id,data_saida,motorista_saida,km_saida,destino,obs,status)VALUES(?,?,?,?,?,?,?,'aberto')",[id,veiculo_id,data_saida,motorista_saida||'',+km_saida||0,destino||'',obs||'']);res.json(get('SELECT*FROM transferencias WHERE id=?',[id]))});
app.put('/api/transferencias/:id',authMiddleware,(req,res)=>{const{data_retorno,motorista_retorno,km_retorno,obs,status,veiculo_id,data_saida,motorista_saida,km_saida,destino}=req.body;run("UPDATE transferencias SET data_retorno=?,motorista_retorno=?,km_retorno=?,obs=?,status=?,veiculo_id=COALESCE(?,veiculo_id),data_saida=COALESCE(?,data_saida),motorista_saida=COALESCE(?,motorista_saida),km_saida=COALESCE(?,km_saida),destino=COALESCE(?,destino) WHERE id=?",[data_retorno||'',motorista_retorno||'',+km_retorno||0,obs||'',status||'aberto',veiculo_id||null,data_saida||null,motorista_saida||null,km_saida||null,destino||null,req.params.id]);res.json(get('SELECT*FROM transferencias WHERE id=?',[req.params.id]))});
app.delete('/api/transferencias/:id',authMiddleware,(req,res)=>{run('DELETE FROM transferencias WHERE id=?',[req.params.id]);res.json({ok:true})});

// MANUTENÇÃO
app.get('/api/manutencoes',authMiddleware,(req,res)=>{const{veiculo_id,status}=req.query;const limit=safeInt(req.query.limit,100,500);let sql="SELECT m.*,v.placa,v.nome AS v_nome,v.marca,v.modelo FROM manutencoes m JOIN veiculos v ON v.id=m.veiculo_id WHERE v.ativo=1";const p=[];if(veiculo_id){sql+=' AND m.veiculo_id=?';p.push(veiculo_id)}if(status){sql+=' AND m.status=?';p.push(status)}sql+=' ORDER BY m.data DESC LIMIT ?';p.push(limit);const rows=all(sql,p);rows.forEach(r=>{r.fotos=all('SELECT filename FROM manutencao_fotos WHERE manutencao_id=?',[r.id]).map(f=>'/uploads/'+f.filename)});res.json(rows)});
app.get('/api/manutencoes/:id',authMiddleware,(req,res)=>{const m=get('SELECT*FROM manutencoes WHERE id=?',[req.params.id]);if(!m)return res.status(404).json({error:'404'});m.fotos=all('SELECT filename FROM manutencao_fotos WHERE manutencao_id=?',[req.params.id]).map(f=>'/uploads/'+f.filename);res.json(m)});
app.post('/api/manutencoes',authMiddleware,(req,res)=>{const{veiculo_id,data,tipo,descricao,oficina,valor,km_atual,proxima_km,proxima_data,status,obs}=req.body;if(!veiculo_id||!data)return res.status(400).json({error:'Obrigatórios'});const id=uid();run("INSERT INTO manutencoes(id,veiculo_id,data,tipo,descricao,oficina,valor,km_atual,proxima_km,proxima_data,status,obs)VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",[id,veiculo_id,data,tipo||'preventiva',descricao||'',oficina||'',+valor||0,+km_atual||0,+proxima_km||0,proxima_data||'',status||'concluido',obs||'']);res.json(get('SELECT*FROM manutencoes WHERE id=?',[id]))});
app.put('/api/manutencoes/:id',authMiddleware,(req,res)=>{const{veiculo_id,data,tipo,descricao,oficina,valor,km_atual,proxima_km,proxima_data,status,obs}=req.body;run("UPDATE manutencoes SET veiculo_id=?,data=?,tipo=?,descricao=?,oficina=?,valor=?,km_atual=?,proxima_km=?,proxima_data=?,status=?,obs=? WHERE id=?",[veiculo_id,data,tipo||'preventiva',descricao||'',oficina||'',+valor||0,+km_atual||0,+proxima_km||0,proxima_data||'',status||'concluido',obs||'',req.params.id]);res.json(get('SELECT*FROM manutencoes WHERE id=?',[req.params.id]))});
app.delete('/api/manutencoes/:id',authMiddleware,(req,res)=>{all('SELECT filename FROM manutencao_fotos WHERE manutencao_id=?',[req.params.id]).forEach(f=>{const fn=safeFn(f.filename);if(!fn)return;const p=safeFilePath(fn);if(p&&fs.existsSync(p))fs.unlinkSync(p)});run('DELETE FROM manutencao_fotos WHERE manutencao_id=?',[req.params.id]);run('DELETE FROM manutencoes WHERE id=?',[req.params.id]);res.json({ok:true})});
app.post('/api/manutencoes/:id/fotos',authMiddleware,upload.array('fotos',20),(req,res)=>{const saved=(req.files||[]).map(f=>{const id=uid();run('INSERT INTO manutencao_fotos(id,manutencao_id,filename)VALUES(?,?,?)',[id,req.params.id,f.filename]);return{id,url:'/uploads/'+f.filename}});res.json(saved)});
app.delete('/api/manutencao-fotos/:fn',authMiddleware,(req,res)=>{const fn=safeFn(req.params.fn);if(!fn)return res.status(400).json({error:'Nome de arquivo inválido'});const p=path.join(UPLOADS_DIR,fn);if(fs.existsSync(p))fs.unlinkSync(p);run('DELETE FROM manutencao_fotos WHERE filename=?',[fn]);res.json({ok:true})});

// KM CONTROL
app.get('/api/km-controle',authMiddleware,(req,res)=>{const mes=validMonth(req.query.mes),controls=all("SELECT * FROM km_controles"),rows=all("SELECT * FROM veiculos WHERE ativo=1 ORDER BY placa").map(v=>buildKmPanelRow(v,mes,controls));res.json({mes,rows})});
app.get('/api/km-controle/:veiculo_id',authMiddleware,(req,res)=>{const v=get("SELECT * FROM veiculos WHERE id=? AND ativo=1",[req.params.veiculo_id]);if(!v)return res.status(404).json({error:'404'});const mes=validMonth(req.query.mes),controls=all("SELECT * FROM km_controles WHERE veiculo_id=?",[v.id]);res.json(buildKmPanelRow(v,mes,controls))});
app.put('/api/km-controle/:veiculo_id',authMiddleware,(req,res)=>{const v=get("SELECT * FROM veiculos WHERE id=? AND ativo=1",[req.params.veiculo_id]);if(!v)return res.status(404).json({error:'404'});const incoming=new Map((Array.isArray(req.body.controles)?req.body.controles:[]).map(c=>[normalizeKmService(c?.servico),c]));KM_SERVICE_TYPES.forEach(t=>{const item=incoming.get(t.key),previsao=Math.max(toNum(item?.previsao_km),0),obs=String(item?.obs||'').trim().slice(0,300);if(previsao>0||obs){run("INSERT OR REPLACE INTO km_controles(id,veiculo_id,servico,previsao_km,obs,atualizado_em)VALUES(COALESCE((SELECT id FROM km_controles WHERE veiculo_id=? AND servico=?),?),?,?,?,?,datetime('now','localtime'))",[v.id,t.key,uid(),v.id,t.key,previsao,obs])}else run("DELETE FROM km_controles WHERE veiculo_id=? AND servico=?",[v.id,t.key])});const mes=validMonth(req.query.mes),controls=all("SELECT * FROM km_controles WHERE veiculo_id=?",[v.id]);res.json(buildKmPanelRow(v,mes,controls))});

// SERVICE NOTES
app.get('/api/notas-servico',authMiddleware,(req,res)=>{const{veiculo_id,mes,busca}=req.query;const limit=safeInt(req.query.limit,100,2000);let sql="SELECT n.*,v.placa,v.nome AS v_nome,v.marca,v.modelo FROM notas_servico n LEFT JOIN veiculos v ON v.id=n.veiculo_id WHERE 1=1";const p=[];if(veiculo_id){sql+=' AND n.veiculo_id=?';p.push(veiculo_id)}if(mes){sql+=" AND substr(n.data,1,7)=?";p.push(mes)}if(busca){sql+=" AND (v.placa LIKE ? OR n.oficina LIKE ? OR n.numero LIKE ? OR EXISTS(SELECT 1 FROM nota_servico_itens i WHERE i.nota_id=n.id AND i.descricao LIKE ?))";const b='%'+busca+'%';p.push(b,b,b,b)}sql+=' ORDER BY n.data DESC,n.criado_em DESC LIMIT ?';p.push(limit);const rows=all(sql,p);rows.forEach(n=>{n.itens=all("SELECT * FROM nota_servico_itens WHERE nota_id=? ORDER BY criado_em,id",[n.id]);n.subtotal=n.itens.reduce((s,it)=>s+((+it.quantidade||0)*(+it.valor||0)),0);Object.assign(n,calcNotaTotals(n.subtotal,n.desconto,n.desconto_tipo));n.total_itens=n.itens.length});res.json(rows)});
app.get('/api/notas-servico/:id',authMiddleware,(req,res)=>{const n=get("SELECT * FROM notas_servico WHERE id=?",[req.params.id]);if(!n)return res.status(404).json({error:'404'});n.itens=all("SELECT * FROM nota_servico_itens WHERE nota_id=? ORDER BY criado_em,id",[n.id]);n.subtotal=n.itens.reduce((s,it)=>s+((+it.quantidade||0)*(+it.valor||0)),0);Object.assign(n,calcNotaTotals(n.subtotal,n.desconto,n.desconto_tipo));res.json(n)});
app.post('/api/notas-servico',authMiddleware,(req,res)=>{const{veiculo_id,data,km_horimetro,oficina,numero,desconto,desconto_tipo,obs}=req.body,itens=normalizeNotaItems(req.body.itens);if(!veiculo_id||!data||!itens.length)return res.status(400).json({error:'Veículo, data e itens obrigatórios'});const id=uid(),subtotal=itens.reduce((s,it)=>s+(it.quantidade*it.valor),0),totals=calcNotaTotals(subtotal,desconto,desconto_tipo);run("INSERT INTO notas_servico(id,veiculo_id,data,km_horimetro,oficina,numero,desconto,desconto_tipo,total,obs)VALUES(?,?,?,?,?,?,?,?,?,?)",[id,veiculo_id,data,toNum(km_horimetro),String(oficina||'').slice(0,200),String(numero||'').slice(0,80),totals.desconto,totals.desconto_tipo,totals.total,String(obs||'').slice(0,1000)]);itens.forEach(it=>run("INSERT INTO nota_servico_itens(id,nota_id,descricao,quantidade,valor)VALUES(?,?,?,?,?)",[uid(),id,it.descricao,it.quantidade,it.valor]));const row=get("SELECT * FROM notas_servico WHERE id=?",[id]);row.itens=all("SELECT * FROM nota_servico_itens WHERE nota_id=? ORDER BY criado_em,id",[id]);row.subtotal=subtotal;Object.assign(row,totals);res.json(row)});
app.put('/api/notas-servico/:id',authMiddleware,(req,res)=>{const exists=get("SELECT id FROM notas_servico WHERE id=?",[req.params.id]);if(!exists)return res.status(404).json({error:'404'});const{veiculo_id,data,km_horimetro,oficina,numero,desconto,desconto_tipo,obs}=req.body,itens=normalizeNotaItems(req.body.itens);if(!veiculo_id||!data||!itens.length)return res.status(400).json({error:'Veículo, data e itens obrigatórios'});const subtotal=itens.reduce((s,it)=>s+(it.quantidade*it.valor),0),totals=calcNotaTotals(subtotal,desconto,desconto_tipo);run("UPDATE notas_servico SET veiculo_id=?,data=?,km_horimetro=?,oficina=?,numero=?,desconto=?,desconto_tipo=?,total=?,obs=? WHERE id=?",[veiculo_id,data,toNum(km_horimetro),String(oficina||'').slice(0,200),String(numero||'').slice(0,80),totals.desconto,totals.desconto_tipo,totals.total,String(obs||'').slice(0,1000),req.params.id]);run("DELETE FROM nota_servico_itens WHERE nota_id=?",[req.params.id]);itens.forEach(it=>run("INSERT INTO nota_servico_itens(id,nota_id,descricao,quantidade,valor)VALUES(?,?,?,?,?)",[uid(),req.params.id,it.descricao,it.quantidade,it.valor]));const row=get("SELECT * FROM notas_servico WHERE id=?",[req.params.id]);row.itens=all("SELECT * FROM nota_servico_itens WHERE nota_id=? ORDER BY criado_em,id",[req.params.id]);row.subtotal=subtotal;Object.assign(row,totals);res.json(row)});
app.delete('/api/notas-servico/:id',authMiddleware,(req,res)=>{run("DELETE FROM nota_servico_itens WHERE nota_id=?",[req.params.id]);run("DELETE FROM notas_servico WHERE id=?",[req.params.id]);res.json({ok:true})});

// MATERIAL DELIVERIES
app.get('/api/entregas-materiais',authMiddleware,(req,res)=>{const{status,mes,busca,veiculo_id}=req.query;const limit=safeInt(req.query.limit,120,2000);let sql="SELECT e.*,v.placa,v.nome AS v_nome FROM entregas_materiais e LEFT JOIN veiculos v ON v.id=e.veiculo_id WHERE 1=1";const p=[];if(status){sql+=' AND e.status=?';p.push(status)}if(mes){sql+=" AND substr(e.data_pedido,1,7)=?";p.push(mes)}if(veiculo_id){sql+=' AND e.veiculo_id=?';p.push(veiculo_id)}if(busca){sql+=" AND (e.cliente LIKE ? OR e.material LIKE ? OR e.fornecedor LIKE ? OR e.cidade LIKE ? OR e.endereco LIKE ?)";const b='%'+busca+'%';p.push(b,b,b,b,b)}sql+=' ORDER BY e.data_pedido DESC,e.criado_em DESC LIMIT ?';p.push(limit);res.json(all(sql,p).map(enrichMaterialRow))});
app.get('/api/entregas-materiais/:id',authMiddleware,(req,res)=>{const row=get("SELECT e.*,v.placa,v.nome AS v_nome FROM entregas_materiais e LEFT JOIN veiculos v ON v.id=e.veiculo_id WHERE e.id=?",[req.params.id]);if(!row)return res.status(404).json({error:'404'});res.json(enrichMaterialRow(row))});
app.post('/api/entregas-materiais',authMiddleware,(req,res)=>{const{data_pedido,data_entrega,cliente,telefone,material,fornecedor,veiculo_id,motorista,quantidade,unidade,valor_custo_unit,valor_venda_unit,frete_custo,frete_cobrado,taxas,status,endereco,cidade,obs}=req.body;if(!data_pedido||!cliente||!material)return res.status(400).json({error:'Data, cliente e material sao obrigatorios'});const id=uid();run("INSERT INTO entregas_materiais(id,data_pedido,data_entrega,cliente,telefone,material,fornecedor,veiculo_id,motorista,quantidade,unidade,valor_custo_unit,valor_venda_unit,frete_custo,frete_cobrado,taxas,status,endereco,cidade,obs)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",[id,data_pedido,String(data_entrega||'').slice(0,10),String(cliente||'').trim().slice(0,200),String(telefone||'').trim().slice(0,40),String(material||'').trim().slice(0,160),String(fornecedor||'').trim().slice(0,200),String(veiculo_id||'').trim().slice(0,80),String(motorista||'').trim().slice(0,160),Math.max(toNum(quantidade),0),String(unidade||'Carrada').trim().slice(0,20)||'Carrada',Math.max(toNum(valor_custo_unit),0),Math.max(toNum(valor_venda_unit),0),Math.max(toNum(frete_custo),0),Math.max(toNum(frete_cobrado),0),Math.max(toNum(taxas),0),normalizeMaterialStatus(status),String(endereco||'').trim().slice(0,300),String(cidade||'').trim().slice(0,120),String(obs||'').trim().slice(0,1200)]);res.json(enrichMaterialRow(get("SELECT e.*,v.placa,v.nome AS v_nome FROM entregas_materiais e LEFT JOIN veiculos v ON v.id=e.veiculo_id WHERE e.id=?",[id])))});
app.put('/api/entregas-materiais/:id',authMiddleware,(req,res)=>{const exists=get("SELECT id FROM entregas_materiais WHERE id=?",[req.params.id]);if(!exists)return res.status(404).json({error:'404'});const{data_pedido,data_entrega,cliente,telefone,material,fornecedor,veiculo_id,motorista,quantidade,unidade,valor_custo_unit,valor_venda_unit,frete_custo,frete_cobrado,taxas,status,endereco,cidade,obs}=req.body;if(!data_pedido||!cliente||!material)return res.status(400).json({error:'Data, cliente e material sao obrigatorios'});run("UPDATE entregas_materiais SET data_pedido=?,data_entrega=?,cliente=?,telefone=?,material=?,fornecedor=?,veiculo_id=?,motorista=?,quantidade=?,unidade=?,valor_custo_unit=?,valor_venda_unit=?,frete_custo=?,frete_cobrado=?,taxas=?,status=?,endereco=?,cidade=?,obs=? WHERE id=?",[data_pedido,String(data_entrega||'').slice(0,10),String(cliente||'').trim().slice(0,200),String(telefone||'').trim().slice(0,40),String(material||'').trim().slice(0,160),String(fornecedor||'').trim().slice(0,200),String(veiculo_id||'').trim().slice(0,80),String(motorista||'').trim().slice(0,160),Math.max(toNum(quantidade),0),String(unidade||'Carrada').trim().slice(0,20)||'Carrada',Math.max(toNum(valor_custo_unit),0),Math.max(toNum(valor_venda_unit),0),Math.max(toNum(frete_custo),0),Math.max(toNum(frete_cobrado),0),Math.max(toNum(taxas),0),normalizeMaterialStatus(status),String(endereco||'').trim().slice(0,300),String(cidade||'').trim().slice(0,120),String(obs||'').trim().slice(0,1200),req.params.id]);res.json(enrichMaterialRow(get("SELECT e.*,v.placa,v.nome AS v_nome FROM entregas_materiais e LEFT JOIN veiculos v ON v.id=e.veiculo_id WHERE e.id=?",[req.params.id])))});
app.delete('/api/entregas-materiais/:id',authMiddleware,(req,res)=>{run("DELETE FROM entregas_materiais WHERE id=?",[req.params.id]);res.json({ok:true})});

// MAQUINAS
function listMaquinasComStatus(){const ms=all("SELECT * FROM maquinas WHERE ativo=1 ORDER BY nome");const ativos=all("SELECT maquina_id,id,operador_nome,inicio FROM percursos WHERE status='em_andamento'");const map=new Map(ativos.map(p=>[p.maquina_id,p]));return ms.map(m=>{const p=map.get(m.id);return{...m,status_atual:p?'em_uso':'disponivel',percurso_ativo:p||null}})}
app.get('/api/maquinas',authMiddleware,(_,res)=>res.json(listMaquinasComStatus()));
app.get('/api/maquinas/:id',authMiddleware,(req,res)=>{const m=get("SELECT * FROM maquinas WHERE id=?",[req.params.id]);if(!m)return res.status(404).json({error:'404'});const p=get("SELECT * FROM percursos WHERE maquina_id=? AND status='em_andamento'",[req.params.id]);res.json({...m,status_atual:p?'em_uso':'disponivel',percurso_ativo:p||null})});
app.post('/api/maquinas',authMiddleware,adminOnly,(req,res)=>{const{nome,codigo,tipo,descricao,ano}=req.body;if(!nome||!codigo)return res.status(400).json({error:'Nome e código são obrigatórios'});const id=uid();try{run("INSERT INTO maquinas(id,nome,codigo,tipo,descricao,ano)VALUES(?,?,?,?,?,?)",[id,String(nome).trim().slice(0,160),String(codigo).trim().slice(0,60),String(tipo||'').trim().slice(0,80),String(descricao||'').trim().slice(0,500),ano?+ano:null]);audit(req,'criar','maquina',id,{nome,codigo});res.json(get("SELECT * FROM maquinas WHERE id=?",[id]))}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'Código já existe':'Erro ao criar máquina'})}});
app.put('/api/maquinas/:id',authMiddleware,adminOnly,(req,res)=>{const{nome,codigo,tipo,descricao,ano,ativo}=req.body;if(!nome||!codigo)return res.status(400).json({error:'Nome e código são obrigatórios'});try{run("UPDATE maquinas SET nome=?,codigo=?,tipo=?,descricao=?,ano=?,ativo=? WHERE id=?",[String(nome).trim().slice(0,160),String(codigo).trim().slice(0,60),String(tipo||'').trim().slice(0,80),String(descricao||'').trim().slice(0,500),ano?+ano:null,ativo!==undefined?+!!ativo:1,req.params.id]);audit(req,'editar','maquina',req.params.id,{nome,codigo});res.json(get("SELECT * FROM maquinas WHERE id=?",[req.params.id]))}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'Código já existe':'Erro ao editar máquina'})}});
app.delete('/api/maquinas/:id',authMiddleware,adminOnly,(req,res)=>{if(get("SELECT id FROM percursos WHERE maquina_id=? AND status='em_andamento'",[req.params.id]))return res.status(400).json({error:'Máquina com percurso em andamento. Encerre primeiro.'});run("UPDATE maquinas SET ativo=0 WHERE id=?",[req.params.id]);audit(req,'desativar','maquina',req.params.id,{});res.json({ok:true})});

// PERCURSOS
function fmtSeg(s){s=Math.max(0,+s||0);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(x).padStart(2,'0')}
app.get('/api/percursos/ativo',authMiddleware,(req,res)=>{const p=get("SELECT * FROM percursos WHERE operador_id=? AND status='em_andamento'",[req.user.uid]);if(!p)return res.json(null);res.json({...p,duracao_seg_atual:Math.floor((Date.now()-new Date(p.inicio).getTime())/1000)})});
app.post('/api/percursos/iniciar',authMiddleware,(req,res)=>{const{maquina_id,lat,lng,endereco}=req.body;if(!maquina_id)return res.status(400).json({error:'Selecione uma máquina'});const m=get("SELECT * FROM maquinas WHERE id=? AND ativo=1",[maquina_id]);if(!m)return res.status(404).json({error:'Máquina não encontrada'});if(get("SELECT id FROM percursos WHERE operador_id=? AND status='em_andamento'",[req.user.uid]))return res.status(409).json({error:'Você já possui um percurso em andamento'});if(get("SELECT id FROM percursos WHERE maquina_id=? AND status='em_andamento'",[maquina_id]))return res.status(409).json({error:'Esta máquina já está em uso'});const motId=req.user.motorista_id||'';const motNome=motId?get("SELECT nome FROM motoristas WHERE id=?",[motId])?.nome||'':'';const id=uid(),inicio=new Date().toISOString();run("INSERT INTO percursos(id,maquina_id,maquina_nome,maquina_codigo,operador_id,operador_nome,motorista_id,motorista_nome,inicio,lat_inicio,lng_inicio,endereco_inicio,status)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'em_andamento')",[id,m.id,m.nome,m.codigo,req.user.uid,req.user.nome,motId,motNome,inicio,lat?+lat:null,lng?+lng:null,String(endereco||'').slice(0,300)]);audit(req,'iniciar_percurso','percurso',id,{maquina_id,maquina:m.nome,lat,lng});res.json(get("SELECT * FROM percursos WHERE id=?",[id]))});
app.post('/api/percursos/encerrar',authMiddleware,(req,res)=>{const{lat,lng,endereco}=req.body;const p=get("SELECT * FROM percursos WHERE operador_id=? AND status='em_andamento'",[req.user.uid]);if(!p)return res.status(404).json({error:'Nenhum percurso em andamento'});const fim=new Date().toISOString(),dur=Math.floor((new Date(fim).getTime()-new Date(p.inicio).getTime())/1000);run("UPDATE percursos SET fim=?,lat_fim=?,lng_fim=?,endereco_fim=?,duracao_seg=?,status='concluido' WHERE id=?",[fim,lat?+lat:null,lng?+lng:null,String(endereco||'').slice(0,300),dur,p.id]);audit(req,'encerrar_percurso','percurso',p.id,{duracao_seg:dur,maquina:p.maquina_nome});res.json(get("SELECT * FROM percursos WHERE id=?",[p.id]))});
app.get('/api/percursos',authMiddleware,adminOnly,(req,res)=>{const{maquina_id,operador_id,status,inicio,fim}=req.query;const limit=safeInt(req.query.limit,200,2000);let sql="SELECT * FROM percursos WHERE 1=1";const p=[];if(maquina_id){sql+=' AND maquina_id=?';p.push(maquina_id)}if(operador_id){sql+=' AND operador_id=?';p.push(operador_id)}if(status){sql+=' AND status=?';p.push(status)}if(inicio){sql+=' AND inicio>=?';p.push(inicio)}if(fim){sql+=' AND inicio<=?';p.push(fim+'T23:59:59')}sql+=' ORDER BY inicio DESC LIMIT ?';p.push(limit);res.json(all(sql,p).map(r=>({...r,duracao_fmt:r.status==='em_andamento'?fmtSeg(Math.floor((Date.now()-new Date(r.inicio).getTime())/1000)):fmtSeg(r.duracao_seg)})))});
app.delete('/api/percursos/:id',authMiddleware,adminOnly,(req,res)=>{const p=get("SELECT * FROM percursos WHERE id=?",[req.params.id]);if(!p)return res.status(404).json({error:'404'});run("DELETE FROM percursos WHERE id=?",[req.params.id]);audit(req,'excluir_percurso','percurso',req.params.id,{maquina:p.maquina_nome,operador:p.operador_nome});res.json({ok:true})});
app.get('/api/percursos/export.csv',authMiddleware,adminOnly,(_,res)=>{const rows=all("SELECT * FROM percursos ORDER BY inicio DESC");const h='Maquina,Codigo,Operador,Motorista,Inicio,Fim,Duracao,Status,LatInicio,LngInicio,EnderecoInicio,LatFim,LngFim,EnderecoFim\n';const csv=h+rows.map(r=>[r.maquina_nome,r.maquina_codigo,r.operador_nome,r.motorista_nome,r.inicio,r.fim,r.status==='em_andamento'?fmtSeg(Math.floor((Date.now()-new Date(r.inicio).getTime())/1000)):fmtSeg(r.duracao_seg),r.status,r.lat_inicio||'',r.lng_inicio||'',r.endereco_inicio||'',r.lat_fim||'',r.lng_fim||'',r.endereco_fim||''].map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');res.setHeader('Content-Disposition','attachment;filename="percursos.csv"');res.setHeader('Content-Type','text/csv;charset=utf-8');res.send('\uFEFF'+csv)});

// AUDITORIA (admin)
app.get('/api/auditoria',authMiddleware,adminOnly,(req,res)=>{const limit=safeInt(req.query.limit,100,500);res.json(all("SELECT * FROM auditoria ORDER BY criado_em DESC LIMIT ?",[limit]))});

// STATS
app.get('/api/stats',authMiddleware,(req,res)=>{const{veiculo_id,inicio,fim}=req.query;let w='WHERE 1=1';const p=[];if(veiculo_id){w+=' AND a.veiculo_id=?';p.push(veiculo_id)}if(inicio){w+=' AND a.data>=?';p.push(inicio)}if(fim){w+=' AND a.data<=?';p.push(fim+'T23:59')}
const geral=get(`SELECT COUNT(*)AS total,COALESCE(SUM(total),0)AS gasto,COALESCE(SUM(litros),0)AS litros,COALESCE(AVG(CASE WHEN consumo>0 THEN consumo END),0)AS media_consumo,COALESCE(AVG(CASE WHEN preco>0 THEN preco END),0)AS preco_medio FROM abastecimentos a ${w}`,p);
const por_mes=all(`SELECT substr(a.data,1,7)AS mes,SUM(a.total)AS total,SUM(a.litros)AS litros,COUNT(*)AS qtd FROM abastecimentos a ${w} GROUP BY mes ORDER BY mes DESC LIMIT 12`,p).reverse();
const por_comb=all(`SELECT a.combustivel,SUM(a.total)AS total,SUM(a.litros)AS litros,COUNT(*)AS qtd FROM abastecimentos a ${w} GROUP BY a.combustivel ORDER BY total DESC`,p);
const por_veiculo=all(`SELECT v.placa,v.nome AS v_nome,v.marca,v.modelo,SUM(a.total)AS total,SUM(a.litros)AS litros,COUNT(*)AS qtd,AVG(CASE WHEN a.consumo>0 THEN a.consumo END)AS media_consumo FROM abastecimentos a JOIN veiculos v ON v.id=a.veiculo_id ${w} AND v.ativo=1 GROUP BY a.veiculo_id ORDER BY total DESC`,p);
const consumo_hist=all(`SELECT substr(a.data,1,10)AS dia,a.consumo,v.placa FROM abastecimentos a LEFT JOIN veiculos v ON v.id=a.veiculo_id ${w} AND a.consumo>0 ORDER BY a.data DESC LIMIT 30`,p).reverse();
const preco_hist=all(`SELECT substr(a.data,1,10)AS dia,a.preco,a.combustivel FROM abastecimentos a ${w} ORDER BY a.data DESC LIMIT 30`,p).reverse();
res.json({geral,por_mes,por_comb,por_veiculo,consumo_hist,preco_hist,fotos_count:get(`SELECT COUNT(*)AS n FROM fotos f JOIN abastecimentos a ON a.id=f.abastecimento_id ${w}`,p)?.n||0,total_veiculos:get('SELECT COUNT(*)AS n FROM veiculos WHERE ativo=1')?.n||0,total_manut:get('SELECT COUNT(*)AS n FROM manutencoes m JOIN veiculos v ON v.id=m.veiculo_id WHERE v.ativo=1')?.n||0,manut_valor:get('SELECT COALESCE(SUM(m.valor),0)AS total FROM manutencoes m JOIN veiculos v ON v.id=m.veiculo_id WHERE v.ativo=1')?.total||0,total_motoristas:get('SELECT COUNT(*)AS n FROM motoristas WHERE ativo=1')?.n||0,alertas_pendentes:get('SELECT COUNT(*)AS n FROM alertas WHERE lido=0 AND resolvido=0')?.n||0})});

app.get('/api/config',authMiddleware,(req,res)=>{const cfg={};all('SELECT chave,valor FROM config').forEach(r=>cfg[r.chave]=r.valor);if(req.user.perfil!=='admin'){delete cfg.smtp_pass;}res.json(cfg)});
const ALLOWED_CONFIG_KEYS=new Set(['empresa','responsavel','alerta_dias_antecedencia','alerta_km_antecedencia','alerta_km_antecedencia_moto','smtp_host','smtp_port','smtp_user','smtp_pass','alerta_email']);
app.post('/api/config',authMiddleware,adminOnly,(req,res)=>{Object.entries(req.body).forEach(([k,v])=>{if(ALLOWED_CONFIG_KEYS.has(k))run('INSERT OR REPLACE INTO config VALUES(?,?)',[k,String(v).slice(0,500)])});res.json({ok:true})});
app.get('/api/export/csv',authMiddleware,(_,res)=>{const rows=all("SELECT a.data,v.placa,v.marca,v.modelo,a.combustivel,a.posto,a.litros,a.preco,a.total,a.hodometro,a.km_rodados,a.consumo,CASE a.cheio WHEN 1 THEN'Sim'ELSE'Nao'END AS cheio,a.nota,a.obs FROM abastecimentos a LEFT JOIN veiculos v ON v.id=a.veiculo_id ORDER BY a.data DESC");const h='Data,Placa,Marca,Modelo,Combustivel,Posto,Litros,Preco,Total,Hodometro,KmRodados,Consumo,Cheio,Nota,Obs\n';const csv=h+rows.map(r=>Object.values(r).map(v=>`"${String(v||'').replace(/"/g,'""')}"`).join(',')).join('\n');res.setHeader('Content-Disposition','attachment;filename="abastecimentos.csv"');res.setHeader('Content-Type','text/csv;charset=utf-8');res.send('\uFEFF'+csv)});

app.get('*',(_,res)=>res.sendFile(path.join(__dirname,'public','index.html')));

try{initDb();app.listen(PORT,()=>{console.log(`\n  iLnet Frota → http://localhost:${PORT}`);console.log(`  Security hardened\n`)})}catch(e){console.error(e);process.exit(1)}
